# Generated by Django 3.2.2 on 2021-05-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_1', '0002_auto_20210507_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework_1.faculty'),
        ),
    ]
