# Generated by Django 3.2.2 on 2021-05-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_1', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homework_1.university'),
        ),
    ]
